<?php /*

This file contains internal information for the Zacky Installer.
Do NOT change. Removing it might prevent you from using the installer 
on this installation in the future.

---
QlpoOTFBWSZTWQTJaagAAJlfgEAQQId/8CHwDRC/79+7MAEZrahqp+inkMk9JgjGoyAaAGaT1BqBGpmjJhI9BAAAAZBoSaaaQ2o0yDTagaNDTTEAS6WGP6Ir2E0mEV5iJvt8FZrAiMzQzLPppdCBzRyGJyVQ5duF5uxxUvGxQeZ5AEeIRU+ATbWFMSNULJEXRDlJjSwAuYLOpDVDqWlklr3McV0huhVgIUux8tKXGOsIJN+7MKBSiAwDVOx3WrBQFbNSg1RS4js+ycbRd+bGAvNcILF+eeASON24CdhGB7zqWh1KmbZcI5xi0C+Zq6qqIsAwRayCt0E12YFjFrDJrhJPLKRsPU4rWY4OcVvMBQygAn0tVal5foYDMc9AEcqKGWu3nDRNDJICirNqSjEhnsVPKe8NTEiXaTOK+aYoSEINNVjfbkqZdUc9RbhAxNOzt/F3JFOFCQBMlpqA

...

*/
